CREATE TABLE BILL (
	BILL_ID BIGINT NOT NULL
	,BILL_AMOUNT FLOAT
	,SERVICE_TAX FLOAT
	,TOTAL_DISCOUT FLOAT
	,SUM FLOAT
	,USER_ID BIGINT
	,PRIMARY KEY (BILL_ID)
	);

CREATE TABLE BILL_ITEM (
	ITEM_ID BIGINT NOT NULL
	,BASE_PRICE FLOAT
	,CATEGORY_DISCOUNT FLOAT
	,PRODUCT_DISCOUNT FLOAT
	,QUANTITY INTEGER
	,SERVICE_TAX FLOAT
	,WEIGHT INTEGER
	,BILL_ID BIGINT
	,PRODUCT_ID BIGINT
	,PRIMARY KEY (ITEM_ID)
	);

CREATE TABLE PRODUCT (
	PRODUCT_ID BIGINT NOT NULL
	,BARCODE BIGINT
	,BASE_PRICE FLOAT
	,DISCOUNT FLOAT
	,PRODUCT_NAME VARCHAR(255)
	,WEIGHT INTEGER
	,CATEGORY_ID BIGINT
	,PRIMARY KEY (PRODUCT_ID)
	);

CREATE TABLE PRODUCT_CATEGORY (
	CATEGORY_ID BIGINT NOT NULL
	,CATEGORY_NAME VARCHAR(255)
	,DISCOUNT FLOAT
	,SERVICE_TAX FLOAT
	,PRIMARY KEY (CATEGORY_ID)
	);

CREATE TABLE USER (
	USER_ID BIGINT NOT NULL
	,EMAIL VARCHAR(255)
	,FIRST_NAME VARCHAR(255)
	,LAST_NAME VARCHAR(255)
	,MOBILE VARCHAR(255)
	,PRIMARY KEY (USER_ID)
	);

ALTER TABLE BILL ADD CONSTRAINT USER_KEY FOREIGN KEY (USER_ID) REFERENCES USER (USER_ID);

ALTER TABLE BILL_ITEM ADD CONSTRAINT BILL_ITEM_PARENT_KEY FOREIGN KEY (BILL_ID) REFERENCES BILL (BILL_ID);

ALTER TABLE BILL_ITEM ADD CONSTRAINT PRODUCT_KEY FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (PRODUCT_ID);

ALTER TABLE PRODUCT ADD CONSTRAINT PRODUCT_PARENT_KEY FOREIGN KEY (CATEGORY_ID) REFERENCES PRODUCT_CATEGORY (CATEGORY_ID);
